modbus:
  - name: wpw_modbus
    type: tcp
    host: !secret wpw_modbus_host_ip
    port: !secret wpw_modbus_port
    delay: 5
    timeout: 10

    sensors:
      - name: MB WPW COP
        unique_id: mb_wpw_cop
        device_address: !secret wpw_modbus_slave
        address: 0x1 #
        input_type: holding
        scale: 0.1
        precision: 1
        unit_of_measurement: ""
        #        data_type: int16
        scan_interval: 30

input_number:
  wpw_p01_heating_setp:
    name: "WPW P01 Heating Setpoint"
    initial: 35
    min: 10
    max: 55
    step: 0.5

  wpw_p02_cooling_setp:
    name: "WPW P01 Cooling Setpoint"
    initial: 20
    min: 12
    max: 30
    step: 0.5

  wpw_p03_temp_diff:
    name: "WPW P03 Temp Diff"
    initial: 2
    min: 2
    max: 18
    step: 0.5

  wpw_p04_hotwater_setp:
    name: "WPW P04 Hotwater Setp"
    initial: 35
    min: 10
    max: 55
    step: 0.5

  wpw_p05_temp_diff:
    name: "WPW P05 Temp Diff"
    initial: 2
    min: 2
    max: 18
    step: 0.5

automation:
  - alias: "Update Modbus wpwp01_heating_setp"
    description: "Sendet den geänderten Wert des Heating Setpoints an Modbus"
    mode: single
    triggers:
      - trigger: state
        entity_id: input_number.wpw_p01_heating_setp
    actions:
      - action: modbus.write_register
        data_template:
          hub: wpw_modbus
          slave: !secret wpw_modbus_slave
          address: 0xCC #
          value: "{{ states('input_number.wpw_p01_heating_setp') |  multiply(2) | int }}"

  - alias: "Update Modbus wpw_p02_cooling_setp"
    description: "Sendet den geänderten Wert des Heating Setpoints an Modbus"
    mode: single
    triggers:
      - trigger: state
        entity_id: input_number.wpw_p02_cooling_setp
    actions:
      - action: modbus.write_register
        data_template:
          hub: wpw_modbus
          slave: !secret wpw_modbus_slave
          address: 0xCB #
          value: "{{ states('input_number.wpw_p02_cooling_setp')| multiply(2) | int }}"

  - alias: "Update Modbus wpw_p03_temp_diff"
    description: "Sendet den geänderten Wert des Heating Setpoints an Modbus"
    mode: single
    triggers:
      - trigger: state
        entity_id: input_number.wpw_p03_temp_diff
    actions:
      - action: modbus.write_register
        data_template:
          hub: wpw_modbus
          slave: !secret wpw_modbus_slave
          address: 0xC6 #
          value: "{{ states('input_number.wpw_p03_temp_diff') }}"

  - alias: "Update Modbus wpw_p04_hotwater_setp"
    description: "Sendet den geänderten Wert des Heating Setpoints an Modbus"
    mode: single
    triggers:
      - trigger: state
        entity_id: input_number.wpw_p04_hotwater_setp
    actions:
      - action: modbus.write_register
        data_template:
          hub: wpw_modbus
          slave: !secret wpw_modbus_slave
          address: 0xCA #
          value: "{{ states('input_number.wpw_p04_hotwater_setp') | multiply(2) | int }}"

  - alias: "Update Modbus wpw_p05_temp_diff"
    description: "Sendet den geänderten Wert des Heating Setpoints an Modbus"
    mode: single
    triggers:
      - trigger: state
        entity_id: input_number.wpw_p05_temp_diff
    actions:
      - action: modbus.write_register
        data_template:
          hub: wpw_modbus
          slave: !secret wpw_modbus_slave
          address: 0xC8 #
          value: "{{ states('input_number.wpw_p05_temp_diff') | multiply(2) | int }}"
