# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml
automation: !include_dir_merge_list automations

#script: !include scripts.yaml
script: !include_dir_merge_named scripts

scene: !include scenes.yaml
utility_meter: !include utility_meters.yaml


# Added by dwerner !env_var
tts:
  - platform: google_translate
    language: "de" # Für deutsche Sprache
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

automation: !include_dir_named automations  
#template: !include_dir_named templates
template: !include templates.yaml

switch: !include_dir_merge_list switches
# Python Scripts aktivieren
#python_script:

# pyscript aktivieren
#pyscript:
#  allow_all_imports: true
#  hass_is_global: true

